### server port
server:
  port: 8081
  servlet:
    context-path: /

## logging
logging:
  level:
    org.springframework.security: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

## keycloak
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/Keneath
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/Keneath
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-name: keneath client
            client-id: keneath_client
            client-secret: 816661e5-19cf-4f3d-ae70-7a1491c277b6
            scope: openid,offline_access,profile
            authorization-grant-type: authorization_code


