### server port
server:
  port: 8081
  servlet:
    context-path: /

## logging
logging:
  level:
    org.springframework.security: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

## keycloak
spring:
  main:
    allow-circular-references: true

keycloak:
  client: client_java_module

saml:
  keystore:
    path: classpath:/saml/keystore.jks
    password: 123456
    alias: client_java_module
  url:
    descriptor: http://localhost:8080/auth/realms/extended_custom_auth_realm_test/protocol/saml/descriptor
